status = [
  "ubuntu_lint",
  "install (2.3.8)",
  "install (2.4.9)",
  "install (2.5.7)",
  "install (2.6.5)",
  "install (jruby-9.2.9.0)",
  "macos (2.4.x)",
  "ubuntu (2.4.x, rubygems)",
  "ubuntu (2.4.x, bundler)",
  "windows (2.4.x)",
  "macos (2.5.x)",
  "ubuntu (2.5.x, rubygems)",
  "ubuntu (2.5.x, bundler)",
  "windows (2.5.x)",
  "macos (2.6.x)",
  "ubuntu (2.6.x, rubygems)",
  "ubuntu (2.6.x, bundler)",
  "windows (2.6.x)",
  "ubuntu_bundler_master (2.6.x)",
  "ruby_master",
  "ubuntu_rvm (2.3.8)",
  "ubuntu_rvm (ruby-head)",
  "ubuntu_rvm (jruby-9.2.9.0)",
]

timeout-sec = 3600
delete_merged_branches = true

[committer]
name = "Bundlerbot"
email = "bot@bundler.io"
