status = [
  "ubuntu_lint",
  "install (2.3.8)",
  "install (2.4.9)",
  "install (2.5.7)",
  "install (2.6.5)",
  "install (jruby-9.2.11.0)",
  "macos (2.4.9)",
  "ubuntu (2.4.9)",
  "windows (2.4.9)",
  "macos (2.5.7)",
  "ubuntu (2.5.7)",
  "windows (2.5.7)",
  "macos (2.6.5)",
  "ubuntu (2.6.5)",
  "windows (2.6.5)",
  "ubuntu (2.3.8)",
  "ubuntu (jruby-9.2.11.0)",
  "windows_bundler (2.4.x)",
  "windows_bundler (2.5.x)",
  "windows_bundler (2.6.x)",
  "ubuntu_bundler_lint",
  "ubuntu_bundler (2.3.8, v2.5.2)",
  "ubuntu_bundler (2.3.8, v2.6.14)",
  "ubuntu_bundler (2.3.8, v2.7.10)",
  "ubuntu_bundler (2.3.8, v3.0.6)",
  "ubuntu_bundler (2.3.8, ..)",
  "ubuntu_bundler (2.4.9, v2.6.14)",
  "ubuntu_bundler (2.4.9, v2.7.10)",
  "ubuntu_bundler (2.4.9, v3.0.6)",
  "ubuntu_bundler (2.4.9, ..)",
  "ubuntu_bundler (2.5.7, v2.7.10)",
  "ubuntu_bundler (2.5.7, v3.0.6)",
  "ubuntu_bundler (2.5.7, ..)",
  "ubuntu_bundler (2.6.5, v3.0.6)",
  "ubuntu_bundler (2.6.5, ..)",
  "ubuntu_bundler3 (2.4.9, v3.0.6)",
  "ubuntu_bundler3 (2.4.9, ..)",
  "ubuntu_bundler3 (2.5.7, v3.0.6)",
  "ubuntu_bundler3 (2.5.7, ..)",
  "ubuntu_bundler3 (2.6.5, v3.0.6)",
  "ubuntu_bundler3 (2.6.5, ..)"
]

timeout_sec = 3600
prerun_timeout_sec = 3600
delete_merged_branches = true

[committer]
name = "Bundlerbot"
email = "bot@bundler.io"
