status = [
  "windows / build (2.6.x) (push)",
  "ubuntu / build (2.6.x, rubygems) (push)".
]

timeout-sec = 14400
delete_merged_branches = true

[committer]
name = "Bundlerbot"
email = "bot@bundler.io"
