AllCops:
  DisabledByDefault: true
  Exclude:
    - 'bundler/**/*'

Layout/CommentIndentation:
  Enabled: true

Layout/IndentationConsistency:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true
