AllCops:
  DisabledByDefault: true
  Exclude:
    - 'bundler/**/*'
    - 'lib/rubygems/resolver/molinillo/**/*'
  TargetRubyVersion: 2.2

Layout/IndentationConsistency:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true
