AllCops:
  DisabledByDefault: true
  Exclude:
    - 'bundler/**/*'
    - 'lib/rubygems/resolver/molinillo/**/*'
  TargetRubyVersion: 2.2

Layout/AccessModifierIndentation:
  Enabled: true

Layout/BlockAlignment:
  Enabled: true

Layout/CaseIndentation:
  Enabled: true

Layout/ClosingParenthesisIndentation:
  Enabled: true

Layout/CommentIndentation:
  Enabled: true

Layout/ElseAlignment:
  Enabled: true

# Force Unix line endings.
Layout/EndOfLine:
  Enabled: true
  EnforcedStyle: lf

Layout/IndentationConsistency:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Style/MutableConstant:
  Enabled: true
