name: daily

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  daily:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        ruby: [ ruby-head ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none
      - name: Show Ruby version
        run: ruby --version
      - name: Test rubygems
        run: |
          rake setup
          rake test

      - uses: actions/download-artifact@v2
        with:
          name: status
          path: previous_status.txt
      - name: Save fail status
        if: failure()
        run: echo "FAIL" > status.txt
      - name: Save pass status
        if: success()
        run: echo "PASS" > status.txt
      - name: Compare with previous run
        run: echo "::set-env name=STATUS_CHANGED::$(diff status.txt previous_status.txt; echo $?)"

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: env.STATUS_CHANGED != '0'

      - uses: actions/upload-artifact@v2
        with:
          name: status
          path: status.txt
    timeout-minutes: 60
