name: daily

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  daily:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        ruby: [ ruby-head ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none

      - name: Show Ruby version
        run: ruby --version

      - name: Test rubygems
        run: |
          rake setup
          rake test

      - uses: actions/download-artifact@v2
        with:
          name: rubygems_status
          path: previous_status.txt
        if: always()

      - name: Save status
        if: always()
        run: echo "${{ job.status }}" > status.txt

      - name: Compare with previous run
        if: always()
        run: echo "::set-env name=STATUS_CHANGED::$(diff status.txt previous_status.txt; echo $?)"

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: env.STATUS_CHANGED != '0'

      - uses: actions/upload-artifact@v2
        with:
          name: rubygems_status
          path: status.txt
        if: always()

    timeout-minutes: 60
