name: install

on:
  pull_request:

  push:
    branches:
      - staging
      - trying

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ 2.3.8, 2.4.9, 2.5.7, 2.6.5, jruby-9.2.11.0 ]
    steps:
      - uses: actions/checkout@v1
      - run: git submodule update -i
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install rubygems
        run: ruby -Ilib -S rake install
    timeout-minutes: 10
