name: jruby-bundler

on:
  pull_request:

  push:
    branches:
      - master

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

defaults:
  run:
    shell: bash
    working-directory: ./bundler

jobs:
  jruby_bundler:
    name: Bundler on JRuby (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    env:
      RGV: ..

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022]

    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      - name: Setup ruby
        uses: ruby/setup-ruby@03b78bdda287ae04217ee12e4b64996630a03542 # v1.131.0
        with:
          ruby-version: jruby-9.3.9.0
          bundler: none
      - name: Setup java
        uses: actions/setup-java@1df8dbefe2a8cbc99770194893dd902763bee34b # v3.9.0
        with:
          distribution: temurin
          java-version: 18.0.0
        if: "!startsWith(matrix.os.name, 'ubuntu')"
      - name: Prepare dependencies
        run: |
          bin/rake spec:parallel_deps
      - name: Run Test
        run: |
          bin/parallel_rspec --tag jruby_only --tag jruby
        if: startsWith(matrix.os.name, 'ubuntu')
      - name: Install local bundler
        run: |
          bin/rake install:local
        if: startsWith(matrix.os.name, 'ubuntu')
      - name: Run a warbler project
        run: |
          cd spec/realworld/fixtures/warbler
          bundle install
          bundle exec warble
          java -jar warbler.jar
        if: startsWith(matrix.os.name, 'ubuntu')
