name: macos

on: [push]

jobs:
  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        ruby: [ '2.3.x', '2.4.x', '2.5.x', '2.6.x' ]
        test_tool: [ "rubygems", "bundler" ]
    steps:
      - uses: actions/checkout@master
      - run: git submodule update -i
      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install Dependencies
        run: util/ci.sh before_script
        env:
          TEST_TOOL: ${{ matrix.test_tool }}
      - name: Run Test
        run: util/ci.sh script
        env:
          TEST_TOOL: ${{ matrix.test_tool }}
