name: ruby-master

on:
  pull_request:

  push:
    branches:
      - staging
      - trying

jobs:
  ruby_master:
    runs-on: ubuntu-latest
    container:
      image: rubylang/ruby:master-nightly-bionic
      env:
        TEST_TOOL: rubygems
    steps:
      - name: Setup Requirements
        run: |
          gem install rake --no-document
      - uses: actions/checkout@v1
      - run: git submodule update -i
      - name: ruby -v
        run: ruby -v
      - name: Run Test
        run: |
          util/ci.sh before_script
          util/ci.sh script
