name: spell

on:
  pull_request:

  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  spell:
    name: Check spelling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      - uses: codespell-project/actions-codespell@22ff5a2e4b591290baf82d47c9feadac31c65441 # v1.0
