name: ubuntu-lint

on:
  pull_request:

  push:
    branches:
      - staging
      - trying

jobs:
  ubuntu_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.5
      - name: Install Dependencies
        run: rake setup
      - name: Run Lint
        run: rake rubocop
      - name: Install Dependencies in Bundler
        run: bin/rake spec:deps
        working-directory: ./bundler
      - name: "Check RVM integration, man:check"
        run: bin/rake check_rvm_integration man:check
        working-directory: ./bundler
    timeout-minutes: 15
