name: ubuntu

on:
  pull_request:

  push:
    branches:
      - staging
      - trying

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.4.9', '2.5.7', '2.6.5' ]
        test_tool: [ "rubygems", "bundler" ]
    steps:
      - uses: actions/checkout@v1
      - run: git submodule update -i
      - name: Fixed world writable dirs
        run: |
          chmod go-w $HOME
          sudo chmod -R go-w /usr/share
          sudo chmod -R go-w /opt
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install Dependencies
        run: util/ci.sh before_script
        env:
          TEST_TOOL: ${{ matrix.test_tool }}
      - name: Run Test
        run: util/ci.sh script
        env:
          TEST_TOOL: ${{ matrix.test_tool }}
    timeout-minutes: 60
