name: ubuntu-lint

on:
  pull_request:

  push:
    branches:
      - staging
      - trying

jobs:
  ubuntu_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.5
      - name: Run Lint
        run: |
          rake setup
          gem install rubocop -v "~>0.74.0"
          util/rubocop
      - name: Run Lint in Bundler
        run: |
          cd bundler
          bin/rake spec:deps
          gem i rake -v "13.0.1"
          bin/rubocop --ignore_parent_exclusion
          bin/rake check_rvm_integration man:check
    timeout-minutes: 15
