name: ubuntu-bundler3

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  ubuntu_bundler3:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ruby: [ 2.4.10, 2.5.8, 2.6.6, 2.7.1 ]
        rgv: [ v3.1.4, .. ]
    env:
      RGV: ${{ matrix.rgv }}
      RUBYOPT: --disable-gems
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
        if: matrix.rgv != '..'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
        if: matrix.rgv == '..'
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none
      - name: Prepare dependencies
        run: |
          BUNDLER_SPEC_SUB_VERSION=3.0.0 bin/rake override_version
          bin/rake spec:parallel_deps
        working-directory: ./bundler
      - name: Run Test
        run: |
          bin/rake spec:all
        working-directory: ./bundler
    timeout-minutes: 60
