name: ubuntu-lint

on:
  pull_request:

  push:
    branches:
      - staging
      - trying

jobs:
  ubuntu_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: git submodule update -i
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6.5"
      - name: Install Dependencies
        run: util/ci.sh before_script
        env:
          TEST_TOOL: rubygems
      - name: Run Lint
        run: util/ci.sh rubocop
        env:
          TEST_TOOL: rubygems
    timeout-minutes: 15
