name: ubuntu-lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: git submodule update -i
      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6.x"
      - name: Install Dependencies
        run: util/ci.sh before_script
        env:
          TEST_TOOL: rubygems
      - name: Run Lint
        run: util/ci.sh rubocop
        env:
          TEST_TOOL: rubygems
