name: ubuntu-bundler-lint

on:
  pull_request:

  push:
    branches:
      - staging
      - trying

jobs:
  ubuntu_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.5
      - name: Install Dependencies
        run: |
          cd bundler
          bin/rake spec:deps
      - name: Run Lint
        run: |
          cd bundler
          bin/rubocop --ignore_parent_exclusion
          bin/rake check_rvm_integration man:check
    timeout-minutes: 15
