name: ubuntu

on:
  pull_request:

  push:
    branches:
      - staging
      - trying

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ 2.3.8, 2.4.9, 2.5.7, 2.6.5, jruby-9.2.9.0 ]
        test_tool: [ rubygems, bundler ]
    steps:
      - uses: actions/checkout@v1
      - run: git submodule update -i
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Run Test
        run: |
          util/ci.sh before_script
          util/ci.sh script
        env:
          TEST_TOOL: ${{ matrix.test_tool }}
        if: matrix.ruby == '2.4.9' || matrix.ruby == '2.5.7' || matrix.ruby == '2.6.5' || matrix.test_tool == 'rubygems'
    timeout-minutes: 60
