name: unstable

on:
  pull_request:

  push:
    branches:
      - staging
      - trying

jobs:
  unstable:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        ruby: [ ruby-head ]
    steps:
      - uses: actions/checkout@v1
      - run: git submodule update -i
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Test bundler
        run: |
          BDV=master util/ci.sh before_script
          util/ci.sh script
        continue-on-error: true
        env:
          TEST_TOOL: bundler
      - name: Test rubygems
        run: |
          util/ci.sh before_script
          util/ci.sh script
        env:
          TEST_TOOL: rubygems
    timeout-minutes: 60
