name: windows-bundler

on:
  pull_request:

  push:
    branches:
      - staging
      - trying

jobs:
  windows_bundler:
    runs-on: windows-latest

    strategy:
      matrix:
        ruby: [ '2.4', '2.5', '2.6' ]

    steps:
      - uses: actions/checkout@v1

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install dependencies
        run: |
          cd bundler
          bin/rake spec:parallel_deps
        shell: bash

      - name: Run specs
        run: |
          cd bundler
          bin/parallel_rspec spec
        shell: bash
