name: windows

on:
  pull_request:

  push:
    branches:
      - staging
      - trying

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        ruby: [ 2.4.9, 2.5.7, 2.6.5 ]
    steps:
      - uses: actions/checkout@v1
      - run: git submodule update -i
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install Dependencies
        run: TEST_TOOL=rubygems util/ci.sh before_script
        shell: bash
      - name: Run Test
        run: |
          ridk enable
          rake test
    timeout-minutes: 15
