name: windows

on:
  pull_request:

  push:
    branches:
      - staging
      - trying

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        ruby: [ 2.4.9, 2.5.7, 2.6.5 ]
    steps:
      - uses: actions/checkout@v1
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install Dependencies
        run: rake setup
        shell: bash
      - name: Run Test
        run: |
          ridk enable
          rake test
      - name: Install dependencies in Bundler
        run: |
          cd bundler
          bin/rake spec:parallel_deps
        shell: bash
      - name: Run specs in Bundler
        run: |
          cd bundler
          bin/parallel_rspec spec
        shell: bash
    timeout-minutes: 15
